"""initial

Revision ID: 759cecd4a7a5
Revises: 
Create Date: 2026-05-06 15:38:55.931051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '759cecd4a7a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('workbook_xml', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_keycloak_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fraction', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('nmec_name_list', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('num_versions', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('zip_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=False)
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_config_id', sa.Integer(), nullable=False),
    sa.Column('exam_xml', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nmec', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('results', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capture_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('answer_key', sa.JSON(), nullable=True),
    sa.Column('relative_weights', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exam_config_id'], ['exam_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('exam_config_id', sa.Integer(), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('relative_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exam_config_id'], ['exam_config.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiting_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_config_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PREPARATION', 'RUNNING', 'CLOSED', name='waitingroomstate'), nullable=False),
    sa.Column('associations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exam_config_id'], ['exam_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_config_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('multiple_students_to_exam', 'multiple_exams_to_student', 'exam_correction_no_student', name='warningtype'), nullable=False),
    sa.Column('student_list', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_list', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exam_config_id'], ['exam_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_option')
    op.drop_table('warning')
    op.drop_table('waiting_room')
    op.drop_table('topic_config')
    op.drop_table('question')
    op.drop_table('exam')
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_table('topic')
    op.drop_table('exam_config')
    op.drop_table('workbook')
    op.drop_table('subject')
    # ### end Alembic commands ###
