"""empty message

Revision ID: 86fd624a8e22
Revises: a99e746df69f
Create Date: 2026-05-18 01:38:30.876680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86fd624a8e22'
down_revision: Union[str, Sequence[str], None] = 'a99e746df69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_config', 'state',
               existing_type=postgresql.ENUM('preparing', 'running', 'closed_and_capture', 'warning_handling', 'validation', 'completed', name='examstate'),
               nullable=True,
               existing_server_default=sa.text("'preparing'::examstate"))
    op.alter_column('exam_config', 'associations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_config', 'associations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('exam_config', 'state',
               existing_type=postgresql.ENUM('preparing', 'running', 'closed_and_capture', 'warning_handling', 'validation', 'completed', name='examstate'),
               nullable=False,
               existing_server_default=sa.text("'preparing'::examstate"))
    # ### end Alembic commands ###
