"""empty message

Revision ID: 92216ae3b654
Revises: 759cecd4a7a5
Create Date: 2026-05-08 23:37:48.581572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92216ae3b654'
down_revision: Union[str, Sequence[str], None] = '759cecd4a7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('student_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('exam', sa.Column('student_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('exam', sa.Column('results_details', sa.JSON(), nullable=True))
    op.add_column('exam', sa.Column('correction_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'correction_path')
    op.drop_column('exam', 'results_details')
    op.drop_column('exam', 'student_email')
    op.drop_column('exam', 'student_name')
    # ### end Alembic commands ###
