sonar.projectKey=PEI-EduPro_app
sonar.organization=pei-edupro

# Sources
sonar.sources=api/src,web/src
sonar.tests=api/tests

# Python
sonar.python.version=3.12
sonar.python.coverage.reportPaths=api/coverage.xml

# TypeScript
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
