services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT}:80"
    volumes:
      - exam_images:/app/images
      - exam_storage:/app/storage
    depends_on:
      db:
        condition: service_healthy

volumes:
  exam_images:
  exam_storage:
