/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUnidadesCurricularesRouteImport } from './routes/_layout/unidades-curriculares'
import { Route as LayoutNovaUcRouteImport } from './routes/_layout/nova-uc'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUnidadesCurricularesRoute =
  LayoutUnidadesCurricularesRouteImport.update({
    id: '/unidades-curriculares',
    path: '/unidades-curriculares',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNovaUcRoute = LayoutNovaUcRouteImport.update({
  id: '/nova-uc',
  path: '/nova-uc',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nova-uc': typeof LayoutNovaUcRoute
  '/unidades-curriculares': typeof LayoutUnidadesCurricularesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nova-uc': typeof LayoutNovaUcRoute
  '/unidades-curriculares': typeof LayoutUnidadesCurricularesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/nova-uc': typeof LayoutNovaUcRoute
  '/_layout/unidades-curriculares': typeof LayoutUnidadesCurricularesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nova-uc' | '/unidades-curriculares'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nova-uc' | '/unidades-curriculares'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/nova-uc'
    | '/_layout/unidades-curriculares'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/unidades-curriculares': {
      id: '/_layout/unidades-curriculares'
      path: '/unidades-curriculares'
      fullPath: '/unidades-curriculares'
      preLoaderRoute: typeof LayoutUnidadesCurricularesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/nova-uc': {
      id: '/_layout/nova-uc'
      path: '/nova-uc'
      fullPath: '/nova-uc'
      preLoaderRoute: typeof LayoutNovaUcRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutNovaUcRoute: typeof LayoutNovaUcRoute
  LayoutUnidadesCurricularesRoute: typeof LayoutUnidadesCurricularesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutNovaUcRoute: LayoutNovaUcRoute,
  LayoutUnidadesCurricularesRoute: LayoutUnidadesCurricularesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
