/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUnidadesCurricularesRouteImport } from './routes/_layout/unidades-curriculares'
import { Route as LayoutNovoExameRouteImport } from './routes/_layout/novo-exame'
import { Route as LayoutNovaUcRouteImport } from './routes/_layout/nova-uc'
import { Route as LayoutMobile_scan_testeRouteImport } from './routes/_layout/mobile_scan_teste'
import { Route as LayoutMobile_evaluate_testsRouteImport } from './routes/_layout/mobile_evaluate_tests'
import { Route as LayoutExamesUcRouteImport } from './routes/_layout/exames-uc'
import { Route as LayoutExamesCorrecaoRouteImport } from './routes/_layout/exames-correcao'
import { Route as LayoutDetalhesUcRouteImport } from './routes/_layout/detalhes-uc'
import { Route as LayoutBancoQuestoesRouteImport } from './routes/_layout/banco-questoes'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUnidadesCurricularesRoute =
  LayoutUnidadesCurricularesRouteImport.update({
    id: '/unidades-curriculares',
    path: '/unidades-curriculares',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNovoExameRoute = LayoutNovoExameRouteImport.update({
  id: '/novo-exame',
  path: '/novo-exame',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNovaUcRoute = LayoutNovaUcRouteImport.update({
  id: '/nova-uc',
  path: '/nova-uc',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMobile_scan_testeRoute = LayoutMobile_scan_testeRouteImport.update({
  id: '/mobile_scan_teste',
  path: '/mobile_scan_teste',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMobile_evaluate_testsRoute =
  LayoutMobile_evaluate_testsRouteImport.update({
    id: '/mobile_evaluate_tests',
    path: '/mobile_evaluate_tests',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutExamesUcRoute = LayoutExamesUcRouteImport.update({
  id: '/exames-uc',
  path: '/exames-uc',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamesCorrecaoRoute = LayoutExamesCorrecaoRouteImport.update({
  id: '/exames-correcao',
  path: '/exames-correcao',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDetalhesUcRoute = LayoutDetalhesUcRouteImport.update({
  id: '/detalhes-uc',
  path: '/detalhes-uc',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBancoQuestoesRoute = LayoutBancoQuestoesRouteImport.update({
  id: '/banco-questoes',
  path: '/banco-questoes',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/banco-questoes': typeof LayoutBancoQuestoesRoute
  '/detalhes-uc': typeof LayoutDetalhesUcRoute
  '/exames-correcao': typeof LayoutExamesCorrecaoRoute
  '/exames-uc': typeof LayoutExamesUcRoute
  '/mobile_evaluate_tests': typeof LayoutMobile_evaluate_testsRoute
  '/mobile_scan_teste': typeof LayoutMobile_scan_testeRoute
  '/nova-uc': typeof LayoutNovaUcRoute
  '/novo-exame': typeof LayoutNovoExameRoute
  '/unidades-curriculares': typeof LayoutUnidadesCurricularesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/banco-questoes': typeof LayoutBancoQuestoesRoute
  '/detalhes-uc': typeof LayoutDetalhesUcRoute
  '/exames-correcao': typeof LayoutExamesCorrecaoRoute
  '/exames-uc': typeof LayoutExamesUcRoute
  '/mobile_evaluate_tests': typeof LayoutMobile_evaluate_testsRoute
  '/mobile_scan_teste': typeof LayoutMobile_scan_testeRoute
  '/nova-uc': typeof LayoutNovaUcRoute
  '/novo-exame': typeof LayoutNovoExameRoute
  '/unidades-curriculares': typeof LayoutUnidadesCurricularesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/banco-questoes': typeof LayoutBancoQuestoesRoute
  '/_layout/detalhes-uc': typeof LayoutDetalhesUcRoute
  '/_layout/exames-correcao': typeof LayoutExamesCorrecaoRoute
  '/_layout/exames-uc': typeof LayoutExamesUcRoute
  '/_layout/mobile_evaluate_tests': typeof LayoutMobile_evaluate_testsRoute
  '/_layout/mobile_scan_teste': typeof LayoutMobile_scan_testeRoute
  '/_layout/nova-uc': typeof LayoutNovaUcRoute
  '/_layout/novo-exame': typeof LayoutNovoExameRoute
  '/_layout/unidades-curriculares': typeof LayoutUnidadesCurricularesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/banco-questoes'
    | '/detalhes-uc'
    | '/exames-correcao'
    | '/exames-uc'
    | '/mobile_evaluate_tests'
    | '/mobile_scan_teste'
    | '/nova-uc'
    | '/novo-exame'
    | '/unidades-curriculares'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/banco-questoes'
    | '/detalhes-uc'
    | '/exames-correcao'
    | '/exames-uc'
    | '/mobile_evaluate_tests'
    | '/mobile_scan_teste'
    | '/nova-uc'
    | '/novo-exame'
    | '/unidades-curriculares'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_layout'
    | '/_layout/banco-questoes'
    | '/_layout/detalhes-uc'
    | '/_layout/exames-correcao'
    | '/_layout/exames-uc'
    | '/_layout/mobile_evaluate_tests'
    | '/_layout/mobile_scan_teste'
    | '/_layout/nova-uc'
    | '/_layout/novo-exame'
    | '/_layout/unidades-curriculares'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/unidades-curriculares': {
      id: '/_layout/unidades-curriculares'
      path: '/unidades-curriculares'
      fullPath: '/unidades-curriculares'
      preLoaderRoute: typeof LayoutUnidadesCurricularesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/novo-exame': {
      id: '/_layout/novo-exame'
      path: '/novo-exame'
      fullPath: '/novo-exame'
      preLoaderRoute: typeof LayoutNovoExameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/nova-uc': {
      id: '/_layout/nova-uc'
      path: '/nova-uc'
      fullPath: '/nova-uc'
      preLoaderRoute: typeof LayoutNovaUcRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mobile_scan_teste': {
      id: '/_layout/mobile_scan_teste'
      path: '/mobile_scan_teste'
      fullPath: '/mobile_scan_teste'
      preLoaderRoute: typeof LayoutMobile_scan_testeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mobile_evaluate_tests': {
      id: '/_layout/mobile_evaluate_tests'
      path: '/mobile_evaluate_tests'
      fullPath: '/mobile_evaluate_tests'
      preLoaderRoute: typeof LayoutMobile_evaluate_testsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exames-uc': {
      id: '/_layout/exames-uc'
      path: '/exames-uc'
      fullPath: '/exames-uc'
      preLoaderRoute: typeof LayoutExamesUcRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exames-correcao': {
      id: '/_layout/exames-correcao'
      path: '/exames-correcao'
      fullPath: '/exames-correcao'
      preLoaderRoute: typeof LayoutExamesCorrecaoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/detalhes-uc': {
      id: '/_layout/detalhes-uc'
      path: '/detalhes-uc'
      fullPath: '/detalhes-uc'
      preLoaderRoute: typeof LayoutDetalhesUcRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/banco-questoes': {
      id: '/_layout/banco-questoes'
      path: '/banco-questoes'
      fullPath: '/banco-questoes'
      preLoaderRoute: typeof LayoutBancoQuestoesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBancoQuestoesRoute: typeof LayoutBancoQuestoesRoute
  LayoutDetalhesUcRoute: typeof LayoutDetalhesUcRoute
  LayoutExamesCorrecaoRoute: typeof LayoutExamesCorrecaoRoute
  LayoutExamesUcRoute: typeof LayoutExamesUcRoute
  LayoutMobile_evaluate_testsRoute: typeof LayoutMobile_evaluate_testsRoute
  LayoutMobile_scan_testeRoute: typeof LayoutMobile_scan_testeRoute
  LayoutNovaUcRoute: typeof LayoutNovaUcRoute
  LayoutNovoExameRoute: typeof LayoutNovoExameRoute
  LayoutUnidadesCurricularesRoute: typeof LayoutUnidadesCurricularesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBancoQuestoesRoute: LayoutBancoQuestoesRoute,
  LayoutDetalhesUcRoute: LayoutDetalhesUcRoute,
  LayoutExamesCorrecaoRoute: LayoutExamesCorrecaoRoute,
  LayoutExamesUcRoute: LayoutExamesUcRoute,
  LayoutMobile_evaluate_testsRoute: LayoutMobile_evaluate_testsRoute,
  LayoutMobile_scan_testeRoute: LayoutMobile_scan_testeRoute,
  LayoutNovaUcRoute: LayoutNovaUcRoute,
  LayoutNovoExameRoute: LayoutNovoExameRoute,
  LayoutUnidadesCurricularesRoute: LayoutUnidadesCurricularesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
