name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Copy env files
        run: |
          cp /etc/edupro/deployment.env deployment/.env
          cp /etc/edupro/web.env web/.env

      - name: Deploy
        working-directory: deployment
        run: docker compose up -d --build
