name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4

      - name: Copy env files
        run: |
          cp /etc/edupro/deployment.env deployment/.env
          cp /etc/edupro/web.env web/.env

      - name: Deploy
        run: ./deployment/deploy.sh
