name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Build images
        working-directory: deployment
        run: docker compose build

      - name: Check migrations are up to date
        working-directory: deployment
        run: |
          docker compose -f docker-compose.db.yml up -d --wait
          docker compose run --rm -e POSTGRES_SERVER=db migrate /app/.venv/bin/alembic check

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2

      - name: Run tests
        run: ./run_tests.sh
